spring:
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitabhafsd/demo1
          clone-on-start: true


server:
  port: 8888
