spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: order-service
  config:
    import: "configserver:http://localhost:8888"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
